FROM marketplace.gcr.io/google/ubuntu1804

SHELL ["/bin/bash", "-c"]

RUN sed -i -e '/multiverse$/d' /etc/apt/sources.list \
 && apt-get -q update \
 && apt-get -y --no-install-recommends --allow-downgrades --fix-broken install \
      gcc cmake ninja-build pkg-config \
      dpkg xz-utils bzip2 \
      libc6-dev libseccomp-dev libseccomp2 \
 && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV CC=/usr/bin/gcc
ENTRYPOINT ["/usr/bin/cmake"]
